// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OrbitPass.Infrastructure.Persistence.Context;

#nullable disable

namespace OrbitPass.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604200535_SeedDataTours")]
    partial class SeedDataTours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrbitPass.Domain.Entities.DataTour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataPartida")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_PARTIDA");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DESTINO");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("PRECO_BASE");

                    b.HasKey("Id");

                    b.ToTable("DATAS_TOUR", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DataPartida = new DateTime(2026, 10, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destino = "Órbita Baixa Terrestre",
                            PrecoBase = 50000.00m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DataPartida = new DateTime(2026, 12, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Destino = "Estação Lunar Artemis",
                            PrecoBase = 250000.00m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DataPartida = new DateTime(2027, 5, 20, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Destino = "Colônia de Marte",
                            PrecoBase = 1500000.00m
                        });
                });

            modelBuilder.Entity("OrbitPass.Domain.Entities.Ingresso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("CODIGO_UNICO");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_COMPRA");

                    b.Property<Guid>("DataTourId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("DATA_TOUR_ID");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("USUARIO_ID");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VALOR_PAGO");

                    b.HasKey("Id");

                    b.HasIndex("CodigoUnico")
                        .IsUnique();

                    b.HasIndex("DataTourId");

                    b.ToTable("INGRESSOS", (string)null);
                });

            modelBuilder.Entity("OrbitPass.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_PAGAMENTO");

                    b.Property<Guid>("IngressoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("INGRESSO_ID");

                    b.Property<int>("Metodo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("METODO");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("IngressoId")
                        .IsUnique();

                    b.ToTable("PAGAMENTOS", (string)null);
                });

            modelBuilder.Entity("OrbitPass.Domain.Entities.Ingresso", b =>
                {
                    b.HasOne("OrbitPass.Domain.Entities.DataTour", "DataTour")
                        .WithMany("Ingressos")
                        .HasForeignKey("DataTourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataTour");
                });

            modelBuilder.Entity("OrbitPass.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("OrbitPass.Domain.Entities.Ingresso", "Ingresso")
                        .WithOne("Pagamento")
                        .HasForeignKey("OrbitPass.Domain.Entities.Pagamento", "IngressoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingresso");
                });

            modelBuilder.Entity("OrbitPass.Domain.Entities.DataTour", b =>
                {
                    b.Navigation("Ingressos");
                });

            modelBuilder.Entity("OrbitPass.Domain.Entities.Ingresso", b =>
                {
                    b.Navigation("Pagamento");
                });
#pragma warning restore 612, 618
        }
    }
}
