DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(TABLE_NAME) INTO V_COUNT from USER_TABLES where TABLE_NAME = '__EFMigrationsHistory';
IF V_COUNT = 0 THEN
Begin
BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"__EFMigrationsHistory" (
    "MigrationId" NVARCHAR2(150) NOT NULL,
    "ProductVersion" NVARCHAR2(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
)';
END;

End;

END IF;
EXCEPTION
WHEN OTHERS THEN
    IF(SQLCODE != -942)THEN
        RAISE;
    END IF;
END;
/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604014054_OrbitPass';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "INGRESSOS" (
        "ID" RAW(16) NOT NULL,
        "USUARIO_ID" RAW(16) NOT NULL,
        "DATA_TOUR_ID" RAW(16) NOT NULL,
        "CODIGO_UNICO" NVARCHAR2(40) NOT NULL,
        "STATUS" NUMBER(10) NOT NULL,
        "DATA_COMPRA" TIMESTAMP(7) NOT NULL,
        "VALOR_PAGO" NUMBER(10,2) NOT NULL,
        CONSTRAINT "PK_INGRESSOS" PRIMARY KEY ("ID")
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604014054_OrbitPass';
IF v_Count = 0 THEN

    BEGIN 
    EXECUTE IMMEDIATE 'CREATE TABLE 
    "PAGAMENTOS" (
        "ID" RAW(16) NOT NULL,
        "INGRESSO_ID" RAW(16) NOT NULL,
        "METODO" NUMBER(10) NOT NULL,
        "STATUS" NUMBER(10) NOT NULL,
        "DATA_PAGAMENTO" TIMESTAMP(7) NOT NULL,
        "VALOR" NUMBER(10,2) NOT NULL,
        CONSTRAINT "PK_PAGAMENTOS" PRIMARY KEY ("ID"),
        CONSTRAINT "FK_PAGAMENTOS_INGRESSOS_INGRESSO_ID" FOREIGN KEY ("INGRESSO_ID") REFERENCES "INGRESSOS" ("ID") ON DELETE CASCADE
    )';
    END;
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604014054_OrbitPass';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE '
    CREATE UNIQUE INDEX "IX_INGRESSOS_CODIGO_UNICO" ON "INGRESSOS" ("CODIGO_UNICO")
    ';
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604014054_OrbitPass';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE '
    CREATE UNIQUE INDEX "IX_PAGAMENTOS_INGRESSO_ID" ON "PAGAMENTOS" ("INGRESSO_ID")
    ';
 END IF;
END;

/

DECLARE
    v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM "__EFMigrationsHistory" WHERE "MigrationId" = N'20260604014054_OrbitPass';
IF v_Count = 0 THEN

    EXECUTE IMMEDIATE '
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES (N''20260604014054_OrbitPass'', N''9.0.0'')
    ';
 END IF;
END;

/

